"""Initial migration

Revision ID: 619fde743948
Revises: 
Create Date: 2025-09-09 18:42:50.902554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '619fde743948'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('file_path')

    # ### end Alembic commands ###
